version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: travellist
    container_name: travellist-app
    restart: unless-stopped
    ports:
      - 80:8000
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - travellist
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: travellist-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - travellist

#  nginx:
#    image: nginx:alpine
#    container_name: travellist-nginx
#    restart: unless-stopped
#    ports:
#      - 6400:80
#    volumes:
#      - ./:/var/www
#      - ./docker-compose/nginx:/etc/nginx/conf.d/
#    networks:
#     - travellist

networks:
  travellist:
    driver: bridge